[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"

[[plugins]]
  package = 'netlify-plugin-env'
  [plugins.inputs]
    mode = 'prefix'

[dev]
  autoLaunch = false
