name: Deploy on release
on:
  release:
    types: ["released"]
jobs:
  merge-main-to-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge main to production
        run: |
          git fetch --unshallow
          git checkout production
          git pull
          git merge --no-ff main -m "$(date +'%Y-%m-%dT%H:%M:%S')"
          git push
